### ISSUE TITLE
[ch07] 跟着教程进行客户端一执行,服务端就挂掉:panic: close of closed channel

### ISSUE THREAD

**Issue by zemochen** [cloudwego/biz-demo#70]
ch07 服务端获取客户端metainfo时, 服务端启动正常,客户端一执行,服务端就崩了,服务端console信息如下:
```
&{Env:test Kitex:{Service:demo_proto Address::8888 EnablePprof:false EnableGzip:false EnableAccessLog:false LogLevel:info LogFileName:log/kitex.log LogMaxSize:10 LogMaxBackups:50 LogMaxAge:3} MySQL:{DSN:%s:%s@tcp(%s:%s)/%s?charset=utf8mb4&parseTime=True&loc=Local} Redis:{Address:127.0.0.1:6379 Username: Password: DB:0} Registry:{RegistryAddress:[127.0.0.1:8500] Username: Password:}}
MYSQL Version: {8.0.37}
demo_proto_client true
panic: close of closed channel

goroutine 33 [running]:
github.com/cloudwego/kitex/pkg/remote/trans/nphttp2/grpc.(*http2Server).HandleStreams(0xc0001692c0, 0x1c387c0?, 0x2055040?)
        C:/Users/**/go/pkg/mod/github.com/cloudwego/kitex@v0.9.1/pkg/remote/trans/nphttp2/grpc/http2_server.go:414 +0x7a3
github.com/cloudwego/kitex/pkg/remote/trans/nphttp2.(*svrTransHandler).OnRead(0xc0001b8690, {0x206efb8, 0xc0001b9020}, {0x2072c50?, 0xc000193720})
        C:/Users/**/go/pkg/mod/github.com/cloudwego/kitex@v0.9.1/pkg/remote/trans/nphttp2/server_handler.go:123 +0x14e
github.com/cloudwego/kitex/pkg/remote/trans/detection.(*svrTransHandler).OnRead(0xc0001b8660, {0x206efb8, 0xc0001b8e10}, {0x2072c50, 0xc000193720})
        C:/Users/**/go/pkg/mod/github.com/cloudwego/kitex@v0.9.1/pkg/remote/trans/detection/server_handler.go:95 +0xbc
github.com/cloudwego/kitex/pkg/remote.(*TransPipeline).OnRead(0xc0004f0cc0, {0x206efb8?, 0xc0001b8e10?}, {0x2072c50, 0xc000193720})
        C:/Users/**/go/pkg/mod/github.com/cloudwego/kitex@v0.9.1/pkg/remote/trans_pipeline.go:129 +0xea
github.com/cloudwego/kitex/pkg/remote/trans/gonet.(*transServer).BootstrapServer.func1()       
        C:/Users/**/go/pkg/mod/github.com/cloudwego/kitex@v0.9.1/pkg/remote/trans/gonet/trans_server.go:101 +0x355
created by github.com/cloudwego/kitex/pkg/remote/trans/gonet.(*transServer).BootstrapServer    
        C:/Users/**/go/pkg/mod/github.com/cloudwego/kitex@v0.9.1/pkg/remote/trans/gonet/trans_server.go:85 +0x85
exit status 2
```

 `echo.go` 服务代码:

```go
package service

import (
	"context"
	"fmt"

	"github.com/bytedance/gopkg/cloud/metainfo"
	"github.com/cloudwego/kitex/pkg/kerrors"
	"github.com/zemochen/go-demo/gomall/demo/demo_proto/kitex_gen/pbapi"
)

type EchoService struct {
	ctx context.Context
} // NewEchoService new EchoService
func NewEchoService(ctx context.Context) *EchoService {
	return &EchoService{ctx: ctx}
}

// Run create note info
func (s *EchoService) Run(req *pbapi.Request) (resp *pbapi.Response, err error) {
	clientName, ok := metainfo.GetPersistentValue(s.ctx, "CLIENT_NAME")
	fmt.Println(clientName, ok)
	if req.Message == "error" {
		return nil, kerrors.NewGRPCBizStatusError(1004001, "client param error")
	}
	return &pbapi.Response{Message: req.Message}, nil
}


```

`client.go`  客户端代码:

```go
package main

import (
	"context"
	"errors"
	"fmt"

	"github.com/bytedance/gopkg/cloud/metainfo"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/pkg/kerrors"
	"github.com/cloudwego/kitex/pkg/klog"
	"github.com/cloudwego/kitex/pkg/transmeta"
	"github.com/cloudwego/kitex/transport"
	consul "github.com/kitex-contrib/registry-consul"
	"github.com/zemochen/go-demo/gomall/demo/demo_proto/conf"
	"github.com/zemochen/go-demo/gomall/demo/demo_proto/kitex_gen/pbapi"
	"github.com/zemochen/go-demo/gomall/demo/demo_proto/kitex_gen/pbapi/echo"
)

func main() {
	r, err := consul.NewConsulResolver(conf.GetConf().Registry.RegistryAddress[0])
	if err != nil {
		panic(err)
	}
	c, err := echo.NewClient("demo_proto",
		client.WithResolver(r),
		client.WithTransportProtocol(transport.GRPC),
		client.WithMetaHandler(transmeta.ClientHTTP2Handler),
	)
	if err != nil {
		panic(err)
	}

	ctx := metainfo.WithPersistentValue(context.Background(), "CLIENT_NAME", "demo_proto_client")

	res, error := c.Echo(ctx, &pbapi.Request{Message: "hello"})
	var bizErr *kerrors.GRPCBizStatusError
	if error != nil {
		ok := errors.As(error, &bizErr)
		if ok {
			fmt.Printf("biz error: %#v\n", bizErr)
		}
		klog.Fatal(error)
	}
	fmt.Printf("%v", res)
}
```

详细代码: https://github.com/zemochen/go-demo/tree/ch07-error/demo/demo_protoc

**Comment by rogerogers** [comment]
目前对Windows支持有点问题，暂时可以通过以下 client 配置解决

```go
c, err := echo.NewClient("demo_proto", client.WithResolver(r),
	// client.WithTransportProtocol(transport.GRPC), 不使用 grpc
	client.WithShortConnection(), // 使用短链接
	client.WithMetaHandler(transmeta.ClientHTTP2Handler),
	client.WithMiddleware(middleware.Middleware),
)
```

**Comment by rogerogers** [comment]
https://github.com/cloudwego/kitex/issues/1154

**Comment by sliverdancer** [comment]
> 目前对Windows支持有点问题，暂时可以通过以下 client 配置解决
> 
> c, err := echo.NewClient("demo_proto", client.WithResolver(r),
> 	// client.WithTransportProtocol(transport.GRPC), 不使用 gRPC
> 	client.WithShortConnection(), // 使用短链接
> 	client.WithMetaHandler(transmeta.ClientHTTP2Handler),
> 	client.WithMiddleware(middleware.Middleware),
> )

middleware我引用了这个包以后，goland就开始大面积爆红了

![Image](https://github.com/user-attachments/assets/099f07ce-9f2f-4a43-8ff5-8873d6658af7)
![Image](https://github.com/user-attachments/assets/c8ec77ff-e1e9-4924-8e59-41a6c2da19bc)
